on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: workflow
jobs:
  test:
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - id: go-cache-paths
        name: Prepare cache path
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - name: Install dependencies
        run: |
          make install
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
      - name: test
        run: make test
